name = input("名字：")
age = int(input("年龄："))
height = int(input("身高："))
weight = float(input("体重："))
year = int(input("经过了几年："))
add_h = float(input("身高增加了："))
add_w = float(input("体重增加了："))

print("我叫",name)
print("今年",age,"岁")
print("我的身高是：",height,"cm")
print("我的体重是：",weight,"kg")
print("经过了",year,"年")
print("我的年龄：",year+age,"岁")
print("我的身高：",height+add_h,"cm")
print("我的体重：",weight+add_w,"kg")